version: '3'
services:
  node-app:
    build: .
    restart: always
    depends_on:
      - rabbitmq
      - mongo
  mongo:
    image: "mongo:latest"
    ports:
      - 27017:27017

  rabbitmq:
    image: "rabbitmq:management"
    ports:
      - "5673:5672"
      - "15672:15672"